package:
  name: dill
  version: "0.2.5"

source:
  git_rev: dill-0.2.5
  git_url: https://github.com/uqfoundation/dill.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
#   imports:
#     -

about:
  home: https://github.com/uqfoundation/dill
  license: BSD
  license_file: LICENSE
