package:
  name: croniter
  version: "0.3.12"

source:
  git_rev: 0.3.12
  git_url: https://github.com/kiorky/croniter.git

requirements:
  build:
    - python
    - setuptools
    - python-dateutil

  run:
    - python

# test:
#   imports:
#     -

about:
  home: https://github.com/kiorky/croniter
  # license:
  # license_file: