package:
  name: flask-cache
  version: "0.13.1"

source:
  # Seems that the 0.13.1 revision wasn't tagged
  # git_rev: 0.13.1
  git_url: https://github.com/thadeusb/flask-cache.git

requirements:
  build:
    - python
    - setuptools
    - flask

  run:
    - python
    - flask

# test:
#   imports:
#     -

about:
  home: https://github.com/thadeusb/flask-cache
  license: BSD
  license_file: LICENSE
