package:
  name: babel
  version: "1.3"

source:
  git_rev: 1.3
  git_url: https://github.com/python-babel/babel.git

requirements:
  build:
    - python
    - setuptools
    - pytz >=0a

  run:
    - python

# test:
#   imports:
#     -

about:
  home: https://github.com/python-babel/babel
  license: BSD
  license_file: LICENSE
