package:
  name: wtforms
  version: "2.1.0"

source:
  git_rev: 2.1
  git_url: https://github.com/wtforms/wtforms.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
#   imports:
#     -

about:
  home: https://github.com/wtforms/wtforms
  license: BSD
  license_file: LICENSE.txt
