package:
  name: gunicorn
  version: "19.3.0"

source:
  git_rev: 19.3
  git_url: https://github.com/benoitc/gunicorn.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
#   imports:
#     -

about:
  home: https://github.com/benoitc/gunicorn
  license: MIT
  license_file: LICENSE
