package:
  name: flask-admin
  version: "1.2.0"

source:
  git_rev: v1.2.0
  git_url: https://github.com/flask-admin/flask-admin.git

requirements:
  build:
    - python
    - setuptools
    - flask >=0.7
    - wtforms

  run:
    - python
    - flask >=0.7
    - wtforms

# test:
#   imports:
#     -

about:
  home: https://github.com/flask-admin/flask-admin
  license: BSD
  license_file: LICENSE
