package:
  name: flask-wtf
  version: "0.12"

source:
  git_rev: v0.12
  git_url: https://github.com/lepture/flask-wtf.git

requirements:
  build:
    - python
    - setuptools
    - flask
    - werkzeug
    - wtforms

  run:
    - python

# test:
#   imports:
#     -

about:
  home: https://github.com/lepture/flask-wtf
  license: BSD
  license_file: LICENSE
