package:
  name: airflow
  version: "1.6.2"

source:
  git_rev: 1.6.2
  git_url: https://github.com/airbnb/airflow.git

requirements:
  build:
    - python
    - setuptools
    - alembic >=0.8.3,<0.9
    - babel >=1.3,<2.0
    - chartkick >=0.4.2,<0.5
    - croniter >=0.3.8,<0.4
    - dill >=0.2.2,<0.3
    - flask >=0.10.1,<0.11
    - flask-admin ==1.2.0
    - flask-cache >=0.13.1,<0.14
    - flask-login ==0.2.11
    - flask-wtf ==0.12
    - future >=0.15.0,<0.16
    - gunicorn >=19.3.0,<20.0
    - jinja2 >=2.7.3,<3.0
    - markdown >=2.5.2,<3.0
    - pandas >=0.15.2,<1.0.0
    - pygments >=2.0.1,<3.0
    - python-dateutil >=2.3,<3
    - requests >=2.5.1,<3
    - setproctitle >=1.1.8,<2
    - sqlalchemy >=0.9.8
    - thrift >=0.9.2,<0.10

  run:
    - python
    - alembic >=0.8.3,<0.9
    - babel >=1.3,<2.0
    - chartkick >=0.4.2,<0.5
    - croniter >=0.3.8,<0.4
    - dill >=0.2.2,<0.3
    - flask >=0.10.1,<0.11
    - flask-admin ==1.2.0
    - flask-cache >=0.13.1,<0.14
    - flask-login ==0.2.11
    - flask-wtf ==0.12
    - future >=0.15.0,<0.16
    - gunicorn >=19.3.0,<20.0
    - jinja2 >=2.7.3,<3.0
    - markdown >=2.5.2,<3.0
    - pandas >=0.15.2,<1.0.0
    - pygments >=2.0.1,<3.0
    - python-dateutil >=2.3,<3
    - requests >=2.5.1,<3
    - setproctitle >=1.1.8,<2
    - sqlalchemy >=0.9.8
    - thrift >=0.9.2,<0.10

# test:
#   imports:
#     -

about:
  home: https://github.com/airbnb/airflow
  license: Apache 2.0
  license_file: LICENSE.txt
