package:
  name: setproctitle
  version: "1.1.9"

source:
  git_rev: version-1.1.9
  git_url: https://github.com/dvarrazzo/py-setproctitle.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
#   imports:
#     -

about:
  home: https://github.com/dvarrazzo/py-setproctitle
  license: BSD
  license_file: COPYRIGHT
